#!/bin/bash

### BEGIN INIT INFO
# Provides:   smtpserver
# Required-Start: $local_fs $remote_fs screen-cleanup
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: SMTP server
### END INIT INFO

#Settings
SERVICE='smtp-server.js'
USERNAME='augustl'
INVOCATION="/home/augustl/local/node-v0.10.31/bin/node /home/augustl/local/smtp-server/smtp-server.js"

ME=`whoami`
as_user() {
  if [ $ME == $USERNAME ] ; then
    bash -c "$1"
  else
    su - $USERNAME -c "$1"
  fi
}

smtpserver_start() {
  if  pgrep -u $USERNAME -f $SERVICE > /dev/null
  then
    echo "$SERVICE is already running!"
  else
    echo "Starting $SERVICE..."
    as_user "/usr/bin/screen -dmS smtp-server $INVOCATION"
    sleep 1
    if pgrep -u $USERNAME -f $SERVICE > /dev/null
    then
      echo "$SERVICE is now running."
    else
      echo "Error! Could not start $SERVICE!"
    fi
  fi
}


smtpserver_stop() {
  if pgrep -u $USERNAME -f $SERVICE > /dev/null
  then
    echo "Stopping $SERVICE"
    as_user "/usr/bin/screen -S smtp-server -X quit"
  else
    echo "$SERVICE was not running."
  fi
  if pgrep -u $USERNAME -f $SERVICE > /dev/null
  then
    echo "Error! $SERVICE could not be stopped."
  else
    echo "$SERVICE is stopped."
  fi
}


case "$1" in
  start)
    smtpserver_start
    ;;
  stop)
    smtpserver_stop
    ;;
  restart)
    smtpserver_stop
    smtpserver_start
    ;;
  status)
    if pgrep -u $USERNAME -f $SERVICE > /dev/null
    then
      echo "$SERVICE is running."
    else
      echo "$SERVICE is not running."
    fi
    ;;
 esac

 exit 0
